
- hosts: kafka
  tasks:
  - name: init kafka_topics
    shell: |
      /opt/kafka/bin/kafka-topics.sh --create --bootstrap-server {{ groups['kafka'][0] }}:9092 --topic {{ item }} || true
    with_items:
      - "{{ kafka_topics }}"
