apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: registryschemas
data:
  Organisation.json: |-
    {
      "$schema":"http://json-schema.org/draft-07/schema",
      "type":"object",
      "properties":{
          "Organisation":{
            "$ref":"#/definitions/Organisation"
          }
      },
      "required":[
          "Organisation"
      ],
      "title":"Organisation",
      "definitions":{
          "Organisation":{
            "$id":"#/definitions/Organisation",
            "type":"object",
            "title":"The Organisation Schema",
            "required":[
                "participantCode",
                "participantName",
                "roles",
                "mobile",
                "status",
                "encryptionCert",
                "endpointUrl"
            ],
            "properties":{
                "participantCode":{
                  "type":"string"
                },
                "hfrCode":{
                  "type":"string"
                },
                "participantName":{
                  "type":"string"
                },
                "roles":{
                  "type":"string"
                },
                "address":{
                  "$ref":"#/definitions/Address"
                },
                "email":{
                  "type":"array",
                  "items":{
                      "type":"string",
                      "format":"email"
                  },
                  "maxItems":3
                },
                "phone":{
                  "type":"array",
                  "items":{
                      "type":"string"
                  },
                  "maxItems":3
                },
                "mobile":{
                  "type":"array",
                  "items":{
                      "type":"string"
                  },
                  "minItems":1,
                  "maxItems":3
                },
                "status":{
                  "type":"string",
                  "enum":[
                      "Created",
                      "Active",
                      "Inactive",
                      "Blocked"
                  ]
                },
                "signingCertPath":{
                  "type":"string",
                  "format":"uri"
                },
                "encryptionCert":{
                  "type":"string",
                  "format":"uri"
                },
                "endpointUrl":{
                  "type":"string",
                  "format":"url"
                },
                "paymentDetails":{
                  "$ref":"#/definitions/paymentDetails"
                }
            }
          },
          "Address":{
            "title": "Address",
            "type":"object",
            "required":[

            ],
            "properties":{
                "plot":{
                  "type":"string"
                },
                "street":{
                  "type":"string"
                },
                "landmark":{
                  "type":"string"
                },
                "locality":{
                  "type":"string"
                },
                "village":{
                  "type":"string"
                },
                "district":{
                  "type":"string"
                },
                "state":{
                  "type":"string"
                },
                "pincode":{
                  "type":"string"
                }
            }
          },
          "paymentDetails":{
            "title": "PaymentDetails",
            "type":"object",
            "required":[

            ],
            "properties":{
                "upiId":{
                  "type":"string"
                },
                "accountNumber":{
                  "type":"string"
                },
                "ifscCode":{
                  "type":"string"
                }
            },
            "oneOf":[
                {
                  "required":[
                      "upiId"
                  ]
                },
                {
                  "required":[
                      "accountNumber",
                      "ifscCode"
                  ]
                }
            ]
          }
      },
      "_osConfig":{
          "ownershipAttributes": [
            {
                "email": "/participantName",
                "mobile": "/participantName",
                "userId": "/participantCode"
            }
          ],
          "uniqueIndexFields":[
            "participantName",
            "participantCode"
          ],
          "subjectJsonPath": "participantName"
      }
    }
  User.json: |-
    {
      "$schema":"http://json-schema.org/draft-07/schema",
      "type":"object",
      "properties":{
        "User":{
          "$ref":"#/definitions/User"
        }
      },
      "required":[
        "User"
      ],
      "title":"User",
      "definitions":{
        "User":{
          "$id":"#/definitions/User",
          "type":"object",
          "title":"The User Schema",
          "required":[
            "userId",
            "userName",
            "roles",
            "tenant",
            "organisationDetails"
          ],
          "properties":{
            "userId":{
              "type":"string"
            },
            "userName":{
              "type":"string"
            },
            "pin":{
              "type":"string"
            },
            "mobile":{
              "type":"string"
            },
            "email":{
              "type":"string",
              "format":"email"
            },
            "roles":{
              "type":"string"
            },
            "tenant":{
              "type":"string"
            },
            "linkedUserId":{
              "type":"string"
            },
            "organisationDetails":{
              "$ref":"#/definitions/organisationDetails"
            }
          }
        },
        "organisationDetails":{
          "title":"organisationDetails",
          "type":"object",
          "required":[
            "organisationName",
            "organisationOSID"
          ],
          "properties":{
            "organisationName":{
              "type":"string"
            },
            "organisationOSID":{
              "type":"string"
            }
          }
        }
      },
      "_osConfig":{
        "ownershipAttributes":[
          {
            "email":"/email",
            "mobile":"/mobile",
            "userId":"/userId"
          }
        ],
        "uniqueIndexFields":[
          "userId"
        ],
        "subjectJsonPath":"userId",
        "attestationAttributes": [
          "organisationDetails"
        ],
        "attestationPolicies":[
          {
            "property": "organisationDetails",
            "paths": [
              "organisationDetails"
            ],
            "attestorEntity": "Organisation",
            "conditions": "(ATTESTOR#$.osid#.contains(REQUESTER#$.organisationOSID#) && ATTESTOR#$.participantName#.contains(REQUESTER#$.organisationName#))"
          }
        ]
      }
    }
